frase = 'Curso em Vídeo Python'
print(frase[3:13])
print(frase[:13])
print(frase[1:15])
print(frase[1:15:3])
print(frase.count('o'))
print(frase.upper().count('O'))
print(len(frase))
print(len(frase.strip()))
print(frase.replace('Python', 'Android'))
print('Curso' in frase)
print(frase.find('Vídeo'))
print(frase.split())